---
- import_tasks: create-user.yml

- name: Install system packages
  become: yes
  apt:
    update_cache: yes
    pkg: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - python-dev
    - libxml2
    - libxml2-dev
    - libxslt1-dev
    - libssl-dev
    - libldap2-dev
    - libsasl2-dev
    - wkhtmltopdf

- name: Create Odoo directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ odoo_default_user }}"
    group: "{{ odoo_default_group }}"
    mode: 02775
  with_items:
    - "{{ odoo_path }}"
    - "{{ odoo_config_path }}"
    - "{{ odoo_modules_path }}"

- name: Create log dir
  become: yes
  file:
    path: "{{ odoo_log_path }}"
    state: directory
    group: "{{ odoo_default_group }}"
    mode: 02775

- name: Create log file
  become: yes
  file:
    path: "{{ odoo_log_path }}/odoo.log"
    group: "{{ odoo_default_group }}"
    state: touch
    mode: 02775

- name: Download Odoo
  get_url:
    url: "{{ odoo_url }}"
    dest: "{{ odoo_download_path }}"
    owner: "{{ odoo_default_user }}"
    group: "{{  odoo_default_group }}"
    
- name: Uncompress downloaded Odoo
  unarchive:
    src: "{{ odoo_download_path }}"
    dest: "{{ odoo_path }}"
    remote_src: yes
    owner: "{{ odoo_default_user }}"
    group: "{{ odoo_default_group }}"
    extra_opts: [--strip-components=1]
    creates: "{{ odoo_path }}/setup.py"

- name: Install Odoo python requirements
  pip:
    requirements: "{{ odoo_path }}/requirements.txt"
    virtualenv: "{{ odoo_venv_path }}"

- import_tasks: virtualenv.yml

- import_tasks: add-service.yml

- name: Install nodejs packages
  become: yes
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - nodejs
    - npm

- name: Install Less CSS via nodejs
  become: yes
  npm:
    name: less
    version: 2.7.2
    global: yes

- name: Create node symlink
  become: yes
  file:
    src: /usr/bin/nodejs
    dest: /usr/bin/node
    state: link  

- name: Get installed Odoo version (if any)
  shell: "{{ odoo_python_path }} {{ odoo_bin_path }} --version | cut -d ' ' -f 3"
  register: odoo_installed_version

- name: Install Odoo
  vars:
    odoo_required_version: "{{ odoo_version }}-{{ odoo_release }}"
  shell: "cd {{ odoo_path }} && {{ odoo_python_path }} setup.py install"
  when: not odoo_installed_version.stdout == odoo_required_version

- name: Add Odoo config
  template:
    src: odoo.conf.j2
    dest: "{{ odoo_config_path }}/odoo.conf"
    mode: 0774
    group: "{{  odoo_default_group }}"

- name: Restart Odoo service
  become: yes
  service:
    name: odoo
    state: restarted

